package com.neilturner.aerialviews.providers.youtube

import java.util.Calendar
import java.util.ArrayDeque
import kotlin.random.Random
import timber.log.Timber

object QueryFormulaEngine {
    private const val TAG = "YouTubeQueries"

    enum class QueryCategory {
        AERIAL,
        NATURE,
    }

    enum class ContentCategory(
        val key: String,
        val queryCategory: QueryCategory,
    ) {
        NATURE("nature", QueryCategory.NATURE),
        ANIMALS("animals", QueryCategory.NATURE),
        DRONE("drone", QueryCategory.AERIAL),
        CITIES("cities", QueryCategory.NATURE),
        SPACE("space", QueryCategory.NATURE),
        OCEAN("ocean", QueryCategory.NATURE),
        WEATHER("weather", QueryCategory.NATURE),
        WINTER("winter", QueryCategory.NATURE),
    }

    data class CategoryPreferences(
        val categoryNature: Boolean = true,
        val categoryAnimals: Boolean = true,
        val categoryDrone: Boolean = true,
        val categoryCities: Boolean = false,
        val categorySpace: Boolean = true,
        val categoryOcean: Boolean = true,
        val categoryWeather: Boolean = false,
        val categoryWinter: Boolean = true,
    ) {
        fun isEnabled(category: ContentCategory): Boolean =
            when (category) {
                ContentCategory.NATURE -> categoryNature
                ContentCategory.ANIMALS -> categoryAnimals
                ContentCategory.DRONE -> categoryDrone
                ContentCategory.CITIES -> categoryCities
                ContentCategory.SPACE -> categorySpace
                ContentCategory.OCEAN -> categoryOcean
                ContentCategory.WEATHER -> categoryWeather
                ContentCategory.WINTER -> categoryWinter
            }
    }

    val aiVideoBlacklist =
        listOf(
            "ai generated",
            "made with ai",
            "generated by ai",
            "created with ai",
            "rendered by ai",
            "sora",
            "runway ml",
            "runway",
            "stable diffusion",
            "midjourney video",
            "pika labs",
            "kling ai",
            "ai nature",
            "ai cinematic",
            "ai animation",
            "ai short film",
            "artificial intelligence video",
            "synthetically generated",
            "ai art video",
            "neural network video",
            "rendered with ai",
            "cgi",
            "cg animation",
            "3d animation",
            "3d render",
            "rendered",
            "procedural",
            "unreal engine",
            "blender render",
            "virtual scenery",
            "fantasy landscape",
            "dreamscape",
        )

    val bumperTitleBlacklist =
        listOf(
            "subscribe",
            "click here",
            "watch more",
            "full video",
            "part 1",
            "part 2",
            "episode",
            "compilation",
            "best of",
            "top 10",
            "reaction",
            "review",
            "unboxing",
            "vlog",
            "travel vlog",
            "travel diary",
            "travel guide",
            "travel film",
            "travel movie",
            "travel cinematic",
            "tour guide",
            "city tour",
            "hotel",
            "resort",
            "things to do",
            "itinerary",
            "road trip",
            "backpacking",
            "backpacker",
            "honeymoon",
            "vacation",
            "vacay",
            "tutorial",
            "how to",
            "wallpaper",
            "background video",
            "animated",
            "animation",
            "cgi",
            "3d",
            "render",
            "rendered",
            "loop",
        )

    val qualitySignals =
        listOf(
            "no music",
            "no talking",
            "slow motion",
            "8k",
            "4k hdr",
            "cinematic",
            "timelapse",
            "real footage",
            "documentary",
            "nature film",
            "wildlife",
        )

    private val categoryQueries =
        linkedMapOf(
            ContentCategory.NATURE to
                listOf(
                    "4k nature walk forest ambient",
                    "4k mountain landscape timelapse",
                    "4k river valley scenic",
                    "4k countryside landscape ambient",
                    "4k waterfall nature",
                    "4k forest river no talking",
                    "4k canyon landscape ambient",
                    "4k national park scenic footage",
                ),
            ContentCategory.ANIMALS to
                listOf(
                    "4k wildlife documentary africa",
                    "4k wildlife nature animals",
                    "4k birds wildlife ambient",
                    "4k safari wildlife footage",
                    "4k wildlife national park",
                    "4k whale documentary ocean",
                    "4k elephants documentary ambient",
                    "4k deer forest wildlife footage",
                ),
            ContentCategory.DRONE to
                listOf(
                    "4k drone aerial landscape",
                    "4k aerial footage nature",
                    "4k drone flyover scenic",
                    "4k aerial nature cinematic",
                    "4k fpv drone landscape",
                    "4k drone fjord cinematic",
                    "4k aerial mountain range no music",
                    "4k drone coastline cinematic",
                ),
            ContentCategory.OCEAN to
                listOf(
                    "4k ocean waves ambient",
                    "4k underwater ocean nature",
                    "4k beach waves relaxing",
                    "4k coral reef underwater",
                    "4k ocean sunset ambient",
                    "4k underwater fish documentary",
                    "4k sea cliffs waves ambient",
                    "4k deep ocean nature film",
                ),
            ContentCategory.SPACE to
                listOf(
                    "4k space earth timelapse",
                    "4k aurora borealis timelapse",
                    "4k milky way night sky timelapse",
                    "4k earth from space nasa",
                    "4k northern lights ambient",
                    "4k iss earth view timelapse",
                    "4k moonrise night sky timelapse",
                    "4k galaxy documentary ambient",
                ),
            ContentCategory.CITIES to
                listOf(
                    "4k city skyline timelapse",
                    "4k city aerial drone",
                    "4k architecture timelapse",
                    "4k city night timelapse",
                    "4k urban landscape ambient",
                    "4k downtown skyline no talking",
                    "4k city sunrise timelapse",
                ),
            ContentCategory.WEATHER to
                listOf(
                    "4k thunderstorm timelapse",
                    "4k storm clouds timelapse",
                    "4k rain nature ambient",
                    "4k lightning storm timelapse",
                    "4k cloud timelapse nature",
                    "4k rain forest storm ambient",
                    "4k fog valley weather timelapse",
                ),
            ContentCategory.WINTER to
                listOf(
                    "4k snow landscape ambient",
                    "4k winter forest snow",
                    "4k arctic landscape timelapse",
                    "4k frozen lake winter",
                    "4k snowfall nature ambient",
                    "4k glacier winter documentary",
                    "4k polar landscape no music",
                    "4k aurora snow landscape",
                ),
        )

    fun generateQueryPool(count: Int = 25): List<String> =
        generateQueryPool(
            count = count,
            prefs = CategoryPreferences(),
            entropySeed = refreshSeed(),
        )

    fun generateQueryPool(
        baseQuery: String,
        count: Int = 25,
        entropySeed: Long = 0L,
        prefs: CategoryPreferences = CategoryPreferences(),
    ): List<String> {
        val categoryPool = generateQueryPool(count = count, prefs = prefs, entropySeed = entropySeed)
        val normalizedBaseQuery = baseQuery.trim()
        if (normalizedBaseQuery.isBlank()) {
            return categoryPool
        }

        return (
            listOf(normalizedBaseQuery) +
                categoryPool +
                listOf("$normalizedBaseQuery 4k", "$normalizedBaseQuery cinematic")
        ).distinct()
            .shuffled(Random(entropySeed xor dailySeed() xor refreshSeed()))
            .take(count)
    }

    fun generateQueryPool(
        count: Int,
        prefs: CategoryPreferences,
        entropySeed: Long = 0L,
    ): List<String> {
        val enabledPools =
            categoryQueries
                .filterKeys(prefs::isEnabled)
                .ifEmpty { defaultPools() }

        val selectedQueries =
            roundRobinQueries(
                pools = enabledPools.mapValues { (category, queries) ->
                    queries
                        .shuffled(seedForCategory(category, entropySeed))
                        .toCollection(ArrayDeque())
                },
                count = count,
            )

        val finalPool = selectedQueries.ifEmpty { SAFE_FALLBACK_QUERIES.take(count) }
        Timber.tag(TAG).d("Generated %s YouTube search variants across %s categories", finalPool.size, enabledPools.size)
        return finalPool
    }

    fun generateFallbackQueryPool(
        baseQuery: String,
        count: Int = 12,
        entropySeed: Long = 0L,
        prefs: CategoryPreferences = CategoryPreferences(),
    ): List<String> {
        val categoryPool =
            generateQueryPool(
                count = (count * 2).coerceAtLeast(16),
                prefs = prefs,
                entropySeed = entropySeed xor 0x51A8C27L,
            )
        val normalizedBaseQuery = baseQuery.trim()

        val fallbackQueries =
            if (normalizedBaseQuery.isBlank()) {
                categoryPool + SAFE_FALLBACK_QUERIES
            } else {
                listOf(
                    normalizedBaseQuery,
                    "$normalizedBaseQuery 4k nature",
                    "$normalizedBaseQuery documentary ambient",
                ) + categoryPool
            }

        return fallbackQueries
            .distinct()
            .shuffled(Random(entropySeed xor weeklySeed() xor refreshSeed()))
            .take(count)
    }

    fun categoryOf(query: String): QueryCategory =
        if (AERIAL_QUERY_REGEX.containsMatchIn(query)) {
            QueryCategory.AERIAL
        } else {
            QueryCategory.NATURE
        }

    fun totalPossibleCombinations(): Long =
        categoryQueries.values.sumOf { queries -> queries.size.toLong() }

    fun freshnessSeed(baseQuery: String): String =
        "${baseQuery.trim()}|${weeklySeed()}|${dailySeed()}|${refreshSeed()}|${timeBucket()}"

    fun categorySignature(prefs: CategoryPreferences): String =
        ContentCategory.entries.joinToString(separator = ",") { category ->
            if (prefs.isEnabled(category)) category.key else "-${category.key}"
        }

    private fun defaultPools(): Map<ContentCategory, List<String>> =
        linkedMapOf(
            ContentCategory.NATURE to categoryQueries.getValue(ContentCategory.NATURE),
            ContentCategory.OCEAN to categoryQueries.getValue(ContentCategory.OCEAN),
            ContentCategory.DRONE to categoryQueries.getValue(ContentCategory.DRONE),
        )

    private fun roundRobinQueries(
        pools: Map<ContentCategory, ArrayDeque<String>>,
        count: Int,
    ): List<String> {
        val selected = mutableListOf<String>()
        val buckets = pools.toMutableMap()

        while (selected.size < count && buckets.isNotEmpty()) {
            val exhausted = mutableListOf<ContentCategory>()

            ContentCategory.entries.forEach { category ->
                val bucket = buckets[category] ?: return@forEach
                val query = bucket.pollFirst()
                if (query != null) {
                    selected += query
                }
                if (bucket.isEmpty()) {
                    exhausted += category
                }
                if (selected.size >= count) {
                    return@forEach
                }
            }

            exhausted.forEach(buckets::remove)
        }

        return selected.distinct().take(count)
    }

    private fun seedForCategory(
        category: ContentCategory,
        entropySeed: Long,
    ): Random =
        when (category) {
            ContentCategory.DRONE -> Random(refreshSeed() xor entropySeed xor category.ordinal.toLong())
            ContentCategory.CITIES,
            ContentCategory.SPACE,
            -> Random(weeklySeed() xor entropySeed xor category.ordinal.toLong())

            else -> Random(dailySeed() xor entropySeed xor category.ordinal.toLong())
        }

    private fun weeklySeed(): Long {
        val calendar = Calendar.getInstance()
        return calendar.get(Calendar.YEAR).toLong() * 1000 + calendar.get(Calendar.WEEK_OF_YEAR)
    }

    private fun dailySeed(): Long {
        val calendar = Calendar.getInstance()
        return calendar.get(Calendar.YEAR).toLong() * 10_000L + calendar.get(Calendar.DAY_OF_YEAR)
    }

    private fun refreshSeed(): Long = System.currentTimeMillis() / (1000L * 60L * 60L * 6L)

    private fun timeBucket(): String =
        when (Calendar.getInstance().get(Calendar.HOUR_OF_DAY)) {
            in 5..9 -> "morning"
            in 10..16 -> "day"
            in 17..20 -> "evening"
            else -> "night"
        }

    private val SAFE_FALLBACK_QUERIES =
        listOf(
            "4k nature ambient",
            "4k landscape timelapse",
            "4k scenic nature",
        )

    private val AERIAL_QUERY_REGEX =
        Regex(
            "(aerial|drone|flyover|flythrough|fpv|bird's eye)",
            RegexOption.IGNORE_CASE,
        )
}
